### ISSUE TITLE
publish.ts Channel Id is hard-coded

### ISSUE THREAD

**Issue by adotterer** [bigcommerce/widget-builder#135]
This was causing an issue when I was publishing to a Multi-Storefront store. If you could please update your publis.ts (I could also make a PR if that's possible):

`
import { log, messages } from '../../messages';
import queryLoader from '../query/queryLoader/queryLoader';
import queryParamsLoader from '../query/queryParamsLoader/queryParamsLoader';
import { publishWidget } from '../api/widget';
import WidgetFileType, { FileLoaderResponse } from '../../types';
import schemaLoader from '../schema/schemaLoader/schemaLoader';

import widgetTemplateLoader from './widgetTemplateLoader/widgetTemplateLoader';
import track from './track';

interface CreateWidgetTemplateReq {
    name: string;
    schema: object;
    template: string;
    storefront_api_query: string;
    channel_id: number;
}

const channelId = process.env.WIDGET_BUILDER_CHANNEL_ID ? parseInt(process.env.WIDGET_BUILDER_CHANNEL_ID, 10) : 1;

const widgetTemplatePayload = (widgetName: string): CreateWidgetTemplateReq => ({
    name: widgetName,
    schema: [],
    template: '',
    storefront_api_query: '',
    channel_id: channelId
});

const publishWidgetTemplate = async (widgetName: string, widgetTemplateDir: string) => {
    const widgetTemplateUuid = track.isTracked(widgetTemplateDir);

    try {
        const widgetConfiguration = await Promise.all([
            widgetTemplateLoader(widgetTemplateDir),
            schemaLoader(widgetTemplateDir),
            queryLoader(widgetTemplateDir),
            queryParamsLoader(widgetTemplateDir),
        ]).then(results => results.reduce(
            (acc: CreateWidgetTemplateReq, current: FileLoaderResponse): CreateWidgetTemplateReq => {
                const { data, type } = current;

                if (type === WidgetFileType.TEMPLATE) {
                    return { ...acc, template: data };
                }

                if (type === WidgetFileType.SCHEMA) {
                    return { ...acc, schema: JSON.parse(data) };
                }

                if (type === WidgetFileType.QUERY) {
                    return { ...acc, storefront_api_query: data };
                }

                return acc;
            }, widgetTemplatePayload(widgetName),
        ));

        const { uuid } = await publishWidget(widgetConfiguration, widgetTemplateUuid);

        if (!widgetTemplateUuid) {
            track.startTracking(widgetTemplateDir, uuid);
            log.success(messages.widgetRelease.success(widgetName));
        } else {
            log.success(`Successfully updated ${widgetName}`);
        }
    } catch {
        log.error(messages.widgetRelease.failure);
    }
};

export default publishWidgetTemplate;
`

**Comment by kchu93** [comment]
Thanks for the heads up on this @adotterer, ive created a PR here! 

https://github.com/bigcommerce/widget-builder/pull/136
