### ISSUE TITLE
widget-builder command not working after installing dependency

### ISSUE THREAD

**Issue by Archit18th** [bigcommerce/widget-builder#141]
Environment:
 Node -v18.16.1
NPM - 9.5.1

Erros on console : 
command : widget-builder -h
errors on console : 
/var/BigcProjects/widget-builder/dist/cli/run/init.js:10
const inquirer_1 = __importDefault(require("inquirer"));
                                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/BigcProjects/widget-builder/node_modules/inquirer/lib/inquirer.js from /var/BigcProjects/widget-builder/dist/cli/run/init.js not supported.
Instead change the require of inquirer.js in /var/BigcProjects/widget-builder/dist/cli/run/init.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/BigcProjects/widget-builder/dist/cli/run/init.js:10:36)
    at Object.<anonymous> (/var/BigcProjects/widget-builder/dist/cli/index.js:12:32) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.1

**Comment by mgarciaebo** [comment]
Maybe this is not the best solution @Archit18th but I needed to downgrade the `inquirer` library to version 8.2.5 (the latest of the 8 branch) to make it work again. I just started downgrading until finding a version that works, so 8.2.5.

I'm still testing and not sure if all the commands work as supposed but at least `widget-builder -h` and `widget-builder publish` do.

These are the commands I executed inside my widget-builder repository copy:

```
npm remove inquirer
npm install inquirer@8.2.5 --save --save-exact
npm run install-cli
```

**Comment by Archit18th** [comment]
Thanks  @mgarciaebo for your valuable solution, it seems we can go with the solution you have given as downgrading the inquirer version works.

More than thanks to you!

**Comment by HATECORO** [comment]
Same error

**Comment by Archit18th** [comment]
Hi @HATECORO you can follow the solution recommended by @mgarciaebo , on my system it's working fine till present date. Just use this command after you installed your dependencies :
npm remove inquirer
npm install inquirer@8.2.5 --save --save-exact
npm run install-cli

Also please make sure to maintain your node version as recommend on the widget builder documentation.

**Comment by Bobspadger** [comment]
Just another voice here to confirm I have had the same issue with the latest version from Github (since the inquirer ^9 change in package.json)

This has been on both my mac and docker builds in gitlab-ci.

Mac:
node --version
v18.15.0
npm --version
9.8.0

Docker:
As above as both pinned to the same versions.

The issue arose when trying to publish widgets, not on installation.

**Comment by christensenep** [comment]
Addressed in https://github.com/bigcommerce/widget-builder/pull/150. Apologies for the wait, thank you for reporting the issue.
