### ISSUE TITLE
Error with "type": "text"

### ISSUE THREAD

**Issue by pbsecomm** [bigcommerce/widget-builder#147]
The below error is thrown when settings type is set to 'text'. 

    "error": "/0/schema/0/sections/0/settings/0/type should be equal to one of the allowed values: alignment, boolean, boxModel, code, color, element, imageManager, input, number, productId, productImage, range, regexInput, select, toggle, typography, visibility",

Text works and is how a text area is created so I don't believe an error should be thrown

https://developer.bigcommerce.com/docs/storefront/widgets/input-reference/settings#text

**Comment by loganwoolf** [comment]
This was fixed by this recent pull request https://github.com/bigcommerce/widget-builder/pull/146

Issue can be closed.
