### ISSUE TITLE
npm run install-cli Error

### ISSUE THREAD

**Issue by jcorona48** [bigcommerce/widget-builder#149]
When I install and try to run widget-builder I get the following error.

![image](https://github.com/bigcommerce/widget-builder/assets/105407871/c1e729ff-608a-4883-b71c-71faf21d7fdf)

To solve it, I looked for a version of inquirer that is compatible with commonjs, the one I found was version ^8.0.0.

![image](https://github.com/bigcommerce/widget-builder/assets/105407871/5b6678f1-2f07-474a-b4ea-73d93ed29713)

**Comment by christensenep** [comment]
This has been address by https://github.com/bigcommerce/widget-builder/pull/150, apologies for the wait and thank you for reporting the issue.
