### ISSUE TITLE
API path error on widget-builder init?

### ISSUE THREAD

**Issue by matt-bailey** [bigcommerce/widget-builder#89]
I'm not sure what I'm doing wrong, but when I enter the API path I get an error saying "please enter a valid url". The url is valid though as far as I can tell...

```
? What is the API Path? https://api.bigcommerce.com
>> Please enter a valid url
```

Can anyone help?

**Comment by matt-bailey** [comment]
Ok, I'm going to answer my own question as the docs don't make it clear - I had to delve into the `init.ts` file to realise that it's looking for the full API path, including your store hash.

For example: `https://api.bigcommerce.com/stores/abcde12345/v3`

**Comment by kchu93** [comment]
Hey @matt-bailey, that is correct! You should be able to find the api path from `Advanced Settings -> API Accounts -> Create API Accounts`. This is required so that widget builder can communicate and make changes to your store (i.e. publishing widgets).
